added more information to question
torproject/support pull request #140
Opened 2020-04-03 22:03 UTC by IkkyOdufade

added more information to question: "Can I use Tor with a browser besides Tor Browser?"

2020-04-03 22:04 UTC, IkkyOdufade commented
Hi @gusgustavo. I've made some corrections. Waiting for your feedback. Thank you.

2020-04-15 18:47 UTC, gusgustavo requested changes
Hi, I just reviewed your PR.

2020-04-15 18:47 UTC, gusgustavo commented on content/tbb/tbb-9/contents.lr
> +1. Hiding your real IP address, so you can't be monitored.
I'd change "so you can't be monitored" to something like "Hiding your real IP address to preserve your online privacy".

2020-04-15 18:47 UTC, gusgustavo commented on content/tbb/tbb-9/contents.lr
> +2. No browsing history being stored, so everything is wiped once you close the browser.
I'd change "everything" to something more specific.

2020-04-15 18:47 UTC, gusgustavo commented on content/tbb/tbb-9/contents.lr
> +4. No third party cookies or fingerprinting following you around, collecting information about you from websites you visit.
Isolates cookies and scripts, to prevent it to collect information about you every time you visit a website.

2020-04-15 18:47 UTC, gusgustavo commented on content/tbb/tbb-9/contents.lr
> +5. Nothing being written on your drive, unlike other browsers that incessantly eat at your drive.
I'd remove the comparison ("unlike other browsers...")

2020-04-15 18:47 UTC, gusgustavo commented on content/tbb/tbb-9/contents.lr
> +6. Cross platform:Works on macOS, Windows, Android and Linux.
A space between platform and Works; and it's GNU/Linux.

2020-04-16 11:33 UTC, IkkyOdufade commented
Hi, @gusgustavo. I've made the corrections you requested. Waiting for your feedback. :)

2022-02-15 20:04 UTC, closed without merging