adds the term hamburger-menu to the glossary
torproject/support pull request #141
Opened 2020-04-03 22:26 UTC by luanafaustini

It has two files: content.lr (with the explanation of hamburger menu and a reference link) and an image (showing what is a hamburger menu using Tor Project website as example).

2020-04-07 06:06 UTC, emmapeel2 requested changes
The text is cool, I think the image will be better if its about the hamburguer menu of Tor Browser, as it is the one we talk about on the docs usually.

2020-04-07 18:35 UTC, luanafaustini commented
could you show me which one you are talking about? I'll gladly change it, but I don't know if I understood.

2020-04-09 13:54 UTC, gusgustavo commented
Hi @luanafaustini, you can see the menu here: https://tb-manual.torproject.org/static/images/security-settings-safest.png (on the top right corner)

2020-04-09 15:12 UTC, luanafaustini commented
Ahh got it! thanks @gusgus 
I'm gonna update it right away.

2020-04-10 14:12 UTC, gusgustavo commented on content/glossary/hamburger-menu/content.lr
> +![hamburger-menu](hamburger-menu.png "Hamburger Menu")
Hey @luanafaustini, just a small modification:
The image should be moved to `assets/static/images/`
And you will need to modify this markdown path too.

2020-04-12 21:54 UTC, luanafaustini commented
Hey @gusgus no problems! Gonna do that. I'm just not sure how the relative path goes. Should it be ![hamburger-menu](assets/static/images/hamburger-menu.png "Hamburger Menu")? Thanks!

2020-04-13 15:17 UTC, gusgustavo commented
Hi @luanafaustini, the relative path should look like [this example](https://raw.githubusercontent.com/torproject/support/master/content/onionservices/onionservices-5/contents.lr):
`![Image of a green onion](/static/images/green-onion.png)`

So, `![Hamburger Menu](/static/images/hamburger-menu.png)` (and the file moved to /assets/static/images/)

2020-04-13 16:30 UTC, luanafaustini commented
all done @gusgustavo

2020-04-14 17:25 UTC, merged