Updated gpg output on - How to verify Tor Browser signature
torproject/support pull request #162
Opened 2020-10-08 16:42 UTC by championquizzer

Updated gpg output on https://support.torproject.org/tbb/how-to-verify-signature/
Addressing this issue: https://gitlab.torproject.org/tpo/web/support/-/issues/123

2020-10-08 17:12 UTC, gusgustavo requested changes

2020-10-08 17:12 UTC, gusgustavo commented on content/tbb/how-to-verify-signature/contents.lr
> +    gpg: key 4E2C6E8793298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" 2 new signatures
Ops, could you remove **2 new signatures** and replace with **imported**

2020-10-08 17:12 UTC, gusgustavo commented on content/tbb/how-to-verify-signature/contents.lr
> +    gpg:         new signatures: 2
Same here, you can leave as the original - **imported: 1** 

I added the output of my console, and normally users will see other output.

2020-10-08 18:13 UTC, championquizzer commented on content/tbb/how-to-verify-signature/contents.lr
> +    gpg: key 4E2C6E8793298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" 2 new signatures
I have made the necessary changes in the latest commit [#557cb38](https://github.com/torproject/support/pull/162/commits/557cb380f5e319094e4c5b198334fa5f70e66e9c)

2020-10-14 02:41 UTC, gusgustavo commented on content/tbb/how-to-verify-signature/contents.lr
> +    gpg: key 4E2C6E8793298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" imported
Please don't change this line ("public key" was removed).

2020-10-14 02:42 UTC, gusgustavo requested changes
Hi, there is one more little change to revert. Could you also squash your commits? Thanks!

2020-10-14 05:59 UTC, championquizzer commented
Hi @gusgustavo, I made the necessary change and squashed the commits. Thanks!

2020-10-16 02:37 UTC, merged