Clarify supported architectures
torproject/support pull request #214
Opened 2021-02-28 18:59 UTC by timdream

I tried to follow the documentation to install the latest Tor on Respbian and I hit a wall. It should be made clear on the document so people can avoid repeating my mistake.

Issues need some review:

- Is there a support doc that explains how to build Tor from source, especially leveraging the Debian infra? If so the paragraph should link to that (I found some but I can't verify it works and I don't want to link to random posts on internet)
- I believe the note on `i386` warning on Ubuntu focal in line 60 should be removed, since the repo does not `i386` anymore (?). I didn't follow the instruction on a Ubuntu to verify.
- Lastly, editorial: Should the new section a "Prerequisite" or I should renumber all the sections?

2021-04-09 17:03 UTC, gusgustavo requested changes
Hi, please check my comments.

1. Installing from source: https://community.torproject.org/onion-services/setup/install/
2. Editorial: I like the "Prerequisite" session without a number.

2021-04-09 17:03 UTC, gusgustavo commented on content/apt/apt-1/contents.lr
> +It should output either `amd64` or `arm64`. The repository does not support other CPU architectures.
amd64, x86_64 or arm64.

2021-04-09 17:03 UTC, gusgustavo commented on content/apt/apt-1/contents.lr
> +> **Note on Respbian:** The package repository does not offer 32-bit ARM architecture (`armhf`) images. You should either build Tor from source, or install the version Debian offers.
I believe the OS is called R**a**spbian.

2021-04-13 11:03 UTC, boklm commented on content/apt/apt-1/contents.lr
> +It should output either `amd64` or `arm64`. The repository does not support other CPU architectures.
`uname -m` will output `x86_64` rather than `amd64`. Maybe `dpkg --print-architecture` should be used instead of `uname -m`.

2021-04-13 11:05 UTC, boklm commented on content/apt/apt-1/contents.lr
> +It should output either `amd64` or `arm64`. The repository does not support other CPU architectures.
Also I still see `i386` packages in https://deb.torproject.org/torproject.org/pool/main/t/tor/ so I don't think `i386` support has been removed, except for `focal`.

2021-04-15 12:52 UTC, gusgustavo commented
Hi, could you squash your commits?

2021-04-16 01:32 UTC, timdream commented
@gusgustavo Done.

2021-04-16 18:05 UTC, gusgustavo approved these changes

2021-04-16 18:05 UTC, merged