issue #40
torproject/support pull request #39
Opened 2019-09-07 00:30 UTC by bigwavedave07

2019-09-11 10:09 UTC, emmapeel2 requested changes

2019-09-11 10:09 UTC, emmapeel2 commented on content/gettor/gettor-3/contents.lr
> +
Maybe you can change here the text to explain that this service is not working anymore, instead of deleting the paragraph.

2019-09-11 23:32 UTC, bigwavedave07 commented
Right, absolutely. 

Sent from my iPhone

> On Sep 11, 2019, at 3:09 AM, emmapeel2 <notifications@github.com> wrote:
> 
> @emmapeel2 requested changes on this pull request.
> 
> In content/gettor/gettor-3/contents.lr:
> 
> > @@ -5,7 +5,7 @@ title: To use GetTor via Twitter.
>  seo_slug: to-use-gettor-via-twitter
>  ---
>  description: 
> -To get links for downloading Tor Browser, send a direct message to <mark><a href="https://twitter.com/get_tor">@get_tor</a></mark> with one of the following codes in it (you don't need to follow the account):
> +
> Maybe you can change here the text to explain that this service is not working anymore, instead of deleting the paragraph.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-09-23 15:03 UTC, emmapeel2 commented
there have been many changes now, and the branch is conflicting. please see the current content and open another PR if you still want to make changes. Thanks!

2019-09-23 16:41 UTC, closed without merging