Add question about TBA on F-Droid
torproject/support pull request #46
Opened 2019-09-09 14:27 UTC by RotationMatrix

The idea is to direct the "Go to F-Droid" download button to this question which instructs users to install using the Guardian Project's repo for now.

related-to: https://dip.torproject.org/web/tpo/issues/24

2019-09-09 17:02 UTC, emmapeel2 requested changes

2019-09-09 17:02 UTC, emmapeel2 commented on content/tormobile/tormobile-6/contents.lr
> +It will be, _soon_. In the meantime you can use F-Droid to download Tor Browser for Android by enabling the <mark><a href="https://guardianproject.info/fdroid/">Guardian Project's Repository</a></mar
Could you please use Markdown links, that are easier for translators and easier to read when writing code?

i.e. instead of:

` <mark><a href="https://guardianproject.info/fdroid/">Guardian Project's Repository</a></mark>`

do:

`[Guardian Project's Repository](https://guardianproject.info/fdroid/)`

2019-09-09 17:02 UTC, emmapeel2 commented on content/tormobile/tormobile-6/contents.lr
> +<mark><a href="https://f-droid.org/en/tutorials/add-repo/">Learn how to add a repository to F-Droid</a></mark>.
same with this other link

2019-09-09 17:09 UTC, RotationMatrix commented on content/tormobile/tormobile-6/contents.lr
> +It will be, _soon_. In the meantime you can use F-Droid to download Tor Browser for Android by enabling the <mark><a href="https://guardianproject.info/fdroid/">Guardian Project's Repository</a></mar
Sure, it's fixed now.

2019-09-11 10:04 UTC, emmapeel2 commented
the content of the original file has changed a lot now. could you please adapt this pull request to the current content?

2019-09-11 10:13 UTC, gusgustavo commented
Just add a new question in the section. This should be tormobile-7.

2019-09-11 11:34 UTC, RotationMatrix commented
On it. Would you like me to squash these commits as well?

2019-09-11 13:15 UTC, RotationMatrix commented
This branch should be ready now.

2019-09-11 15:57 UTC, merged