New question: Does my ISP know if I'm using Tor?
torproject/support pull request #80
Opened 2019-10-19 03:03 UTC by PROTechThor

Fixing this issue: https://dip.torproject.org/torproject/web/community/issues/91

2019-10-21 11:44 UTC, gusgustavo requested changes
Good work! There are some changes to be made :)

2019-10-21 11:44 UTC, gusgustavo commented on content/tbb/why-isp-not-block-tor/contents.lr
> +You can prevent your ISP from knowing this by using a VPN.
You can prevent your ISP from knowing this by using a Bridge.

2019-10-21 11:44 UTC, gusgustavo commented on content/tbb/why-isp-not-block-tor/contents.lr
> +Using a VPN with Tor is not recommended, so you should consider using [bridges](https://tb-manual.torproject.org/bridges/) instead.
We don't need a VPN to make a private access to the tor network.

2019-10-21 11:44 UTC, gusgustavo commented on content/tbb/why-isp-not-block-tor/contents.lr
> +Yes, some governments or network admistrators may be able to block Tor. They can get the list of Tor relays and block them.
We should say that the list of Tor relays is public.

2019-10-21 11:44 UTC, gusgustavo commented on content/tbb/why-isp-not-block-tor/contents.lr
> +### If a company bans you from using Tor, what can you do to continue using?
We should replace "company" with something more generic.

2019-10-21 11:44 UTC, gusgustavo commented on content/tbb/why-isp-not-block-tor/contents.lr
> +You can bypass this by using [bridges](https://tb-manual.torproject.org/bridges/).
I'm merging Circumvention Tools and Pluggable Transports page. 
The new one will be /circumvention.

2019-10-23 01:18 UTC, PROTechThor commented
@gusgustavo Hi. What do you think of the changes?

2022-02-15 20:04 UTC, closed without merging