NoScript documentation improvement
torproject/support pull request #83
Opened 2019-10-20 22:41 UTC by PROTechThor

Addressing this issue: https://dip.torproject.org/torproject/web/support/issues/20

2019-10-21 10:11 UTC, gusgustavo requested changes

2019-10-21 10:11 UTC, gusgustavo commented on content/tbb/tbb-25/contents.lr
> +You can enable or disable NoScript on Tor Browser by going to the add-ons manager.
We should not teach users how to disable NoScript like this. They can set it to the "standard" level in Security Settings.

2019-10-21 10:11 UTC, gusgustavo commented on content/tbb/tbb-25/contents.lr
> +The NoScript changes incurred by this are kept even after quitting the browser.
Add also that security level changes is global: it affects all the open tabs.

2019-10-21 10:11 UTC, gusgustavo commented on content/tbb/tbb-25/contents.lr
> +The NoScript changes incurred by this are kept even after quitting the browser.
And since JavaScript is an attack vector against the Tor Browser, it is recommended to use the 'safer' option and most websites will work normally.

2019-10-23 01:52 UTC, PROTechThor commented
@gusgustavo I've made changes :D

2019-10-24 07:14 UTC, emmapeel2 requested changes
nice stuff! only a little nitpickin' as usual :blush:

2019-10-24 07:14 UTC, emmapeel2 commented on content/tbb/tbb-25/contents.lr
> +NoScript provides protection against Cross-site scripting (XSS), CSRF (Cross-site request forgery), clickjacking, man-in-the-middle attacks, and DNS rebinding.
Can we add some links to this attacks?
Maybe we have them on the glossary, or in any case we should add at least some like XSS

2019-10-24 07:14 UTC, emmapeel2 commented on content/tbb/tbb-25/contents.lr
> +The changes incurred by modifying the Secuirity Level affect all open tabs and are kept even after quitting the browser.
little typo in Security

2019-10-24 07:14 UTC, emmapeel2 commented on content/tbb/tbb-25/contents.lr
> +If you believe this is a Tor Browser issue, please report it on our [bug tracker](https://trac.torproject.org/).
Maybe better a link to give feedback? https://support.torproject.org/misc/bug-or-feedback/

2019-10-25 19:44 UTC, PROTechThor commented
@emmapeel2 All good now?

2020-01-15 11:12 UTC, emmapeel2 requested changes

2020-01-15 11:12 UTC, emmapeel2 commented on content/tbb/tbb-25/contents.lr
> +NoScript provides protection against [Cross-site scripting (XSS)](https://support.torproject.org/misc/glossary/#cross-site-scripting-xss), [Cross-site request forgery (CSRF)](https://support.torproje
Please add only an internal link, i.e. `[Cross-site scripting (XSS)](/misc/glossary/#cross-site-scripting-xss)`

2022-02-15 20:04 UTC, closed without merging